project_id = "uhhpnjyceobdcxqviouy"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.generate-report]
verify_jwt = false

[functions.improve-evolution]
verify_jwt = false
